import prisma from '@/lib/prisma';
import { AppError } from '@/lib/errors';
import { CalculatePayrollDto, QueryPayrollDto } from './payroll.schema';

export class PayrollService {
  async calculate(staffId: number, targetMonth: string) {
    if (!/^\d{4}-(0[1-9]|1[0-2])$/.test(targetMonth)) {
      throw new AppError('BAD_REQUEST', 400, 'Invalid targetMonth format. Must be YYYY-MM');
    }

    const [yearStr, monthStr] = targetMonth.split('-');
    const year = parseInt(yearStr, 10);
    const month = parseInt(monthStr, 10);

    const startOfMonth = new Date(year, month - 1, 1);
    const endOfMonth = new Date(year, month, 1);

    const staff = await prisma.staff.findUnique({
      where: { id: staffId },
    });

    if (!staff || staff.deletedAt) {
      throw new AppError('NOT_FOUND', 404, 'Staff not found');
    }

    const taxRule = await prisma.taxRule.findUnique({
      where: { year },
    });

    if (!taxRule) {
      throw new AppError('NOT_FOUND', 404, `TaxRule for year ${year} not found`);
    }

    // Sessions count
    const sessionCount = await prisma.attendance.count({
      where: {
        staffId,
        checkedAt: {
          gte: startOfMonth,
          lt: endOfMonth,
        },
      },
    });

    // Commission rules
    const commissionRule = await prisma.commissionRule.findFirst({
      where: {
        staffId,
        minSessions: { lte: sessionCount },
        maxSessions: { gte: sessionCount },
        OR: [
          { effectiveFrom: null, effectiveTo: null },
          {
            effectiveFrom: { lte: endOfMonth },
            OR: [
              { effectiveTo: null },
              { effectiveTo: { gte: startOfMonth } }
            ]
          }
        ]
      },
      orderBy: { id: 'desc' }
    });

    let sessionPay = 0;
    let salesIncentive = 0; 
    let grossSales = 0;

    if (commissionRule) {
      if (commissionRule.type === 'PER_SESSION') {
        sessionPay = sessionCount * commissionRule.rate;
      } else if (commissionRule.type === 'PERCENT_SALES') {
        // Calculate grossSales generated by this staff's subscriptions within the month
        const payments = await prisma.payment.findMany({
          where: {
            paidAt: { gte: startOfMonth, lt: endOfMonth },
            isRefunded: false,
            subscription: { staffId },
          },
        });
        
        grossSales = payments.reduce((acc, p) => acc + p.amount, 0);
        salesIncentive = Math.floor(grossSales * commissionRule.rate);
      } else if (commissionRule.type === 'FIXED_BONUS') {
        salesIncentive = commissionRule.rate;
      }
    }

    const basePay = staff.baseSalary || 0;
    const totalGrossPay = basePay + sessionPay + salesIncentive;

    let nationalPension = 0;
    let healthInsurance = 0;
    let longTermCare = 0;
    let employmentIns = 0;
    let incomeTax = 0;
    let localIncomeTax = 0;

    if (staff.isFreelancer) {
      incomeTax = Math.floor(totalGrossPay * taxRule.freelancerTax);
      localIncomeTax = Math.floor(incomeTax * 0.1);
    } else {
      nationalPension = Math.floor(totalGrossPay * taxRule.nationalPension);
      healthInsurance = Math.floor(totalGrossPay * taxRule.healthInsurance);
      longTermCare = Math.floor(healthInsurance * taxRule.longTermCareRate);
      employmentIns = Math.floor(totalGrossPay * taxRule.employmentIns);
      
      // Defaults to 0 since tax scales aren't provided statically. Normally external input logic here
      incomeTax = 0;
      localIncomeTax = Math.floor(incomeTax * 0.1);
    }

    const totalDeduction = nationalPension + healthInsurance + longTermCare + employmentIns + incomeTax + localIncomeTax;
    const finalNetPay = totalGrossPay - totalDeduction;
    const severanceAccrual = Math.floor(finalNetPay / 12);

    // Perform Upsert mapping via isolated transaction block
    return await prisma.$transaction(async (tx) => {
      const payroll = await tx.payroll.upsert({
        where: {
          staffId_targetMonth: { staffId, targetMonth },
        },
        create: {
          staffId,
          targetMonth,
          basePay,
          sessionPay,
          salesIncentive,
          totalGrossPay,
          nationalPension,
          healthInsurance,
          longTermCare,
          employmentIns,
          incomeTax,
          localIncomeTax,
          totalDeduction,
          finalNetPay,
          severanceAccrual,
        },
        update: {
          basePay,
          sessionPay,
          salesIncentive,
          totalGrossPay,
          nationalPension,
          healthInsurance,
          longTermCare,
          employmentIns,
          incomeTax,
          localIncomeTax,
          totalDeduction,
          finalNetPay,
          severanceAccrual,
        },
      });

      await tx.severanceLedger.upsert({
        where: { staffId },
        create: {
          staffId,
          totalAccumulated: severanceAccrual,
        },
        update: {
          totalAccumulated: { increment: severanceAccrual },
          lastUpdated: new Date(),
        },
      });

      return payroll;
    });
  }

  async findAll(query?: QueryPayrollDto) {
    return await prisma.payroll.findMany({
      where: {
        staffId: query?.staffId,
        targetMonth: query?.targetMonth,
      },
      orderBy: { targetMonth: 'desc' },
      include: { staff: true },
    });
  }
}

export const payrollService = new PayrollService();
